export const feedData = [
  {
    id: 1,
    username: "Software Developer",
    time: "1h",
    profileImg: "/images/diamond.jpg",
    postImg: "/images/diamond.jpg",
    mutualFrndimg1: "/images/signout picture.jpg",
    mutualFrndimg2: "/images/gold.jpg",
    likeCount: "3,000, 000",
    caption: "Too Young to be Unhappy.",
    commentCount: "108",
  },
  {
    id: 2,
    username: "Osazee Frank",
    time: "3h",
    profileImg: "/images/testimony.jpg",
    postImg: "/images/Frank2.jpg",
    mutualFrndimg1: "/images/harmonry.jpg",
    mutualFrndimg2: "/images/signout picture.jpg",
    likeCount: "100, 000",
    caption: "Everyday is a gift From God",
    commentCount: "500",
  },
  {
    id: 3,
    username: "Irorere Joseph",
    time: "3h",
    profileImg: "/images/joseph.jpg",
    postImg: "/images/spaggeti.jpg",
    mutualFrndimg1: "/images/tolu.jpg",
    mutualFrndimg2: "/images/gold.jpg",
    likeCount: "3,000, 000",
    caption: "Too Young to be Unhappy.",
    commentCount: "108",
  },
  {
    id: 4,
    username: "Harmony",
    time: "4h",
    profileImg: "/images/harmonry.jpg",
    postImg: "/images/profilepicture.jpg",
    mutualFrndimg1: "/images/silver.jpg",
    mutualFrndimg2: "/images/ebony2.jpg",
    likeCount: "3,000, 000",
    caption: "Blessed Soul",
    commentCount: "108",
  },
  {
    id: 5,
    username: "Silver",
    time: "5h",
    profileImg: "/images/silver.jpg",
    postImg: "/images/tolu.jpg",
    mutualFrndimg1: "/images/tolu.jpg",
    mutualFrndimg2: "/images/gold.jpg",
    likeCount: "6,000, 000",
    caption: "Party of One.",
    commentCount: "448",
  },
  {
    id: 6,
    username: "Olatubora Felix",
    time: "5h",
    profileImg: "/images/mr-felix.jpg",
    postImg: "/images/felix.jpg",
    mutualFrndimg1: "/images/Frank2.jpg",
    mutualFrndimg2: "/images/diamond.jpg",
    likeCount: "5,000, 000",
    caption: "Party of One.",
    commentCount: "448",
  },
  {
    id: 7,
    username: "NailedByJhay",
    time: "1s",
    profileImg: "/images/NailedByJhay.jpg",
    postImg: "/images/NailedByJhay.jpg",
    mutualFrndimg1: "/images/Frank2.jpg",
    mutualFrndimg2: "/images/diamond.jpg",
    likeCount: "7,000, 000",
    caption: "Party of One.",
    commentCount: "448",
  },
  {
    id: 8,
    username: "Abies Riches",
    time: "2m",
    profileImg: "/images/ebony.jpg",
    postImg: "/images/Abies_Riches.jpg",
    mutualFrndimg1: "/images/Frank2.jpg",
    mutualFrndimg2: "/images/diamond.jpg",
    likeCount: "7,000, 000",
    caption: "Party of One.",
    commentCount: "48",
  },
  {
    id: 9,
    username: "Ifueko Testimony",
    time: "1m",
    profileImg: "/images/testimony.jpg",
    postImg: "/images/ifueko.jpg",
    mutualFrndimg1: "/images/Frank2.jpg",
    mutualFrndimg2: "/images/diamond.jpg",
    likeCount: "1,000",
    caption: "Party of One.",
    commentCount: "448",
  },
  {
    id: 10,
    username: "Ibude Excellent",
    time: "10m",
    profileImg: "/images/joseph2.jpg",
    postImg: "/images/corperateDay.jpg",
    mutualFrndimg1: "/images/Frank2.jpg",
    mutualFrndimg2: "/images/diamond.jpg",
    likeCount: "1,000",
    caption: "Party of One.",
    commentCount: "448",
  },
  {
    id: 11,
    username: "Inspector Anne",
    time: "45m",
    profileImg: "/images/inspector.jpg",
    postImg: "/images/ebony2.jpg",
    mutualFrndimg1: "/images/Frank2.jpg",
    mutualFrndimg2: "/images/diamond.jpg",
    likeCount: "9,000,000",
    caption: "Party of One.",
    commentCount: "448",
  },
  {
    id: 12,
    username: "Ebony Billions",
    time: "45m",
    profileImg: "/images/ebony.jpg",
    postImg: "/images/Goodlife.jpg",
    mutualFrndimg1: "/images/Frank2.jpg",
    mutualFrndimg2: "/images/diamond.jpg",
    likeCount: "1,000,000",
    caption: "Party of One.",
    commentCount: "948",
  },
];
