export const feedData = [
  {
    id: 1,
    username: "Diamond",
    time: "1h",
    profileImg: "/images/diamond.jpg",
    postImg: "/images/diamond.jpg",
    mutualFrndimg1: "/images/tolu.jpg",
    mutualFrndimg2: "/images/gold.jpg",
    likeCount: "3,000, 000",
    caption: "Too Young to be Unhappy.",
    commentCount: "108",
  },
  {
    id: 2,
    username: "Testimony",
    time: "3h",
    profileImg: "/images/testimony.jpg",
    postImg: "/images/Frank2.jpg",
    mutualFrndimg1: "/images/frank.jpg",
    mutualFrndimg2: "/images/joseph.jpgg",
    likeCount: "100, 000",
    caption: "Everyday is a gift From God",
    commentCount: "500",
  },
  {
    id: 3,
    username: "Joseph",
    time: "3h",
    profileImg: "/images/frank.jpg",
    postImg: "/images/spaggeti.jpg",
    mutualFrndimg1: "/images/tolu.jpg",
    mutualFrndimg2: "/images/gold.jpg",
    likeCount: "3,000, 000",
    caption: "Too Young to be Unhappy.",
    commentCount: "108",
  },
  {
    id: 4,
    username: "Harmony",
    time: "4h",
    profileImg: "/images/harmonry.jpg",
    postImg: "/images/profilepicture.jpg",
    mutualFrndimg1: "/images/silver.jpg",
    mutualFrndimg2: "/images/ebony2.jpg",
    likeCount: "3,000, 000",
    caption: "Blessed Soul",
    commentCount: "108",
  },
  {
    id: 5,
    username: "Silver",
    time: "5h",
    profileImg: "/images/silver.jpg",
    postImg: "/images/tolu.jpg",
    mutualFrndimg1: "/images/tolu.jpg",
    mutualFrndimg2: "/images/gold.jpg",
    likeCount: "6,000, 000",
    caption: "Party of One.",
    commentCount: "448",
  },
];
